name: books_app
description: Flutter hobby project to List, Search, View details, Favorite and even Read books from Google Books API.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.2.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.2.2
  flutter_widget_from_html: ^0.15.2
  extended_image: ^8.0.0
  webview_all: ^0.4.5
  connectivity_plus: ^6.0.5
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.3.2
  firedart: ^0.9.8
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.6

  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon_512.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/app_icon_512.png"
    background_color: "#ffffff"
    theme_color: "#0065ff"
  windows:
    generate: true
    image_path: "assets/icons/app_icon_512.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/app_icon_512.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/


  fonts:
    - family: Prata
      fonts:
        - asset: assets/fonts/Prata-Regular.ttf

    - family: Jost
      fonts:
        - asset: assets/fonts/Jost-Light.ttf
          weight: 100
        - asset: assets/fonts/Jost-Regular.ttf
          weight: 500
        - asset: assets/fonts/Jost-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Jost-Bold.ttf
          weight: 700


