name: books_app
description: Flutter hobby project to List, Search, View details, Favorite and even Read books from Google Books API.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/books/


  fonts:
    - family: Prata
      fonts:
        - asset: assets/fonts/Prata-Regular.ttf


