name: Android CI

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'
          channel: 'stable'
          cache: flutter

      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --dart-define=FIREBASE_KEY=${{ secrets.FIREBASE_KEY }} --dart-define=FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }} --dart-define=GOOGLE_BOOKS_API_KEY=${{ secrets.GOOGLE_BOOKS_API_KEY }}

      - name: Build Linux Binary
        run: flutter build linux --release

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v3
        with:
          name: android-app.apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload Linux binary as artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux-release
          path: build/linux/x64/release/bundle/

      - name: Extract Version
        id: extract_version
        run: |
          version=$(grep '^version:' pubspec.yaml | awk '{print $2}' | tr -d '\r')
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/app-release.apk", "build/linux/x64/release/bundle/"
          tag: v${{ env.VERSION }}-build-${{ github.run_number }}
          token: ${{ secrets.BOOKSAPPCI }}
